# Generated by Django 5.2.5 on 2025-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slideimage',
            name='image_file',
            field=models.CharField(blank=True, help_text='Path to image in static/slideshows, e.g. "myimage.jpg"', max_length=200, null=True),
        ),
    ]
