# Generated by Django 5.2.5 on 2025-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0002_remove_slideimage_image_url_slideimage_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimage',
            name='image_file',
        ),
        migrations.AddField(
            model_name='slideimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slideshows/'),
        ),
    ]
